language: python

sudo: false

addons:
  apt:
    sources:
      # https://bugreports.qt.io/browse/QTBUG-64928?focusedCommentId=389951&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-389951
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
      - xvfb

python:
  - 3.5
  - 3.6

env:
  - TOXENV=core
  - TOXENV=twisted
  - TOXENV=asyncio
  - TOXENV=wheel

install:
  - pip install tox-travis
  - python -m pip install -r requirements.test

script:
  - tox -vvvvvvvv
  - tox -e codecov

deploy:
  provider: pypi
  user: altendky
  password: $PYPI_PASSWORD
  on:
    branch: develop
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  distributions: bdist_wheel
